---
version: '3.2'

services:
  client:
    build: .
    image: jamesbeake/tab-tracker:0.1
    container_name: tab-tracker-vue
    ports:
      - "8080:8080"
    command: ["run", "dev"]
    volumes:
      - ./app/client:/app

  server:
    image:  jamesbeake/tab-tracker:0.1
    container_name: tab-tracker-express
    ports:
      - "3000:3000"
    command: ["start"]
    volumes:
      - ./app/server:/app
#volumes:
