FROM node:8.5.0-alpine

COPY app/server /app

WORKDIR /app
RUN npm install

#VOLUME ["/app/data", "/app/src", "/app/package-lock.json", "/app/package.json"]

EXPOSE 3000

ENTRYPOINT ["npm"]
CMD ["start"]
